name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: spyoungtech/mirror-action@master
      with:
        secrets: GIT_PASSWORD
        args:
          https://github.com/rosran/trackerRepo.git
      env:
        GIT_USERNAME: rosran 
